# Generated by Django 4.2.6 on 2023-10-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='po',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
