# Generated by Django 4.2.6 on 2023-10-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otwdc',
            unique_together={('mat_code', 'gcn_no', 'po_no', 'po_sl_no')},
        ),
        migrations.RemoveField(
            model_name='otwdc',
            name='fin_year',
        ),
    ]
