# Generated by Django 4.2.6 on 2023-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_partmaster_id_alter_po_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='open_po_validity',
            field=models.DateField(null=True),
        ),
    ]
