# Generated by Django 4.2.6 on 2023-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_po_open_po_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwdc',
            name='part_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
