# Generated by Django 4.2.6 on 2023-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_po_part_id_alter_po_po_no_alter_po_total_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inwdc',
            unique_together={('grn_no', 'po_no', 'po_sl_no')},
        ),
        migrations.RemoveField(
            model_name='otwdc',
            name='total_price',
        ),
        migrations.AddField(
            model_name='inwdc',
            name='rework_dc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='qty_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='qty_delivered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otwdc',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='open_po',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='inwdc',
            name='fin_year',
        ),
    ]
