# Generated by Django 4.2 on 2023-10-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0005_alter_inwdc_part_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="otwdc",
            name="rejected_item",
            field=models.BooleanField(default=False),
        ),
    ]
