# Generated by Django 4.2.6 on 2023-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_inwdc_unique_together_remove_otwdc_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwdc',
            name='grn_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='part_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='part_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='po_no',
            field=models.CharField(max_length=20),
        ),
    ]
