# Generated by Django 4.2.6 on 2023-10-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_inwdc_grn_no_alter_inwdc_part_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='consignee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='uom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
