# Generated by Django 4.2 on 2023-10-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_alter_otwdc_gcn_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otwdc",
            name="part_id",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="otwdc", name="po_no", field=models.CharField(max_length=15),
        ),
    ]
