# Generated by Django 4.2 on 2023-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_alter_otwdc_part_id_alter_otwdc_po_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otwdc",
            name="grn_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
