# Generated by Django 4.2.6 on 2023-10-21 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_invoice_alter_inwdc_consignee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='po',
            name='open_po_validty',
        ),
        migrations.AddField(
            model_name='po',
            name='open_po_validity',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='grn_date',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='inwdc',
            name='po_date',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='otwdc',
            name='gcn_date',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='otwdc',
            name='grn_date',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_date',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
    ]
