# Generated by Django 4.2 on 2023-10-25 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_delete_invoice_remove_po_open_po_validty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inwdc",
            name="grn_date",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.AlterField(
            model_name="inwdc",
            name="po_date",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.AlterField(
            model_name="otwdc",
            name="gcn_date",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.AlterField(
            model_name="otwdc",
            name="grn_date",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.AlterField(
            model_name="po",
            name="open_po_validity",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
        migrations.AlterField(
            model_name="po",
            name="po_date",
            field=models.DateField(default=datetime.date(2023, 10, 25)),
        ),
    ]
