# Generated by Django 4.2 on 2023-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_alter_inwdc_grn_date_alter_inwdc_po_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="po",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="po", name="po_no", field=models.CharField(max_length=20),
        ),
    ]
