# Generated by Django 4.2 on 2023-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_po_id_alter_po_po_no"),
    ]

    operations = [
        migrations.RemoveField(model_name="po", name="id",),
        migrations.AlterField(
            model_name="po",
            name="po_no",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
