# Generated by Django 4.2 on 2023-10-26 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_remove_po_id_alter_po_po_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inwdc",
            name="grn_date",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
        migrations.AlterField(
            model_name="inwdc",
            name="po_date",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
        migrations.AlterField(
            model_name="otwdc",
            name="gcn_date",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
        migrations.AlterField(
            model_name="otwdc",
            name="grn_date",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
        migrations.AlterField(
            model_name="po",
            name="open_po_validity",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
        migrations.AlterField(
            model_name="po",
            name="po_date",
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
    ]
