# Generated by Django 4.2.5 on 2023-10-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gstrates',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gststatecode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inwdc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matcompanies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='otwdc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='partmaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='po',
            options={'managed': True},
        ),
    ]
